import React from "react";

import type { NextPage } from "next";
import Head from "next/head";

import {
  Background,
  NavBar,
  Aboutme,
  Contact,
  Projects,
  FadeInSection,
} from "../components";
import { FaArrowDown } from "react-icons/fa";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Pijus Serapinas</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="bg-black w-screen h-screen smooth-scroll block">
        <Background />
        <NavBar className="absolute top-8 flex justify-evenly w-screen" />
        <h1 className="text-white text-5xl absolute bottom-20 left-5 sm:bottom-36 font-semibold sm:font-black sm:left-24 text-center">
          Pijus Serapinas
          <br />
          welcome 😁
        </h1>
        <div className="absolute animate-bounce flex justify-center w-full bottom-0">
          <FaArrowDown color={"#00000"} size={35} />
        </div>
      </div>
      <FadeInSection>
        <div className="block">
          <Aboutme />
        </div>
      </FadeInSection>
      <FadeInSection>
        <div className="block">
          <Projects />
        </div>
      </FadeInSection>
      <FadeInSection>
        <div className="block">
          <Contact />
        </div>
      </FadeInSection>
    </>
  );
};

export default Home;
